DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEE (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   FIRST_NAME VARCHAR(50)NOT NULL,
   LAST_NAME VARCHAR(50)NOT NULL,
   SALARY INT NOT NULL
);

create table CERTIFICATE (
   id INT NOT NULL auto_increment,
   certificate_name VARCHAR(30) default NULL,
   employee_id INT default NULL,
   PRIMARY KEY (id)
);